//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Integral.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface MasterInterfacePrx extends com.zeroc.Ice.ObjectPrx
{
    default void receiveTaskInfo(String function, String lowerLimit, String upperLimit, int integrationMethod, int iterations)
    {
        receiveTaskInfo(function, lowerLimit, upperLimit, integrationMethod, iterations, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void receiveTaskInfo(String function, String lowerLimit, String upperLimit, int integrationMethod, int iterations, java.util.Map<String, String> context)
    {
        _iceI_receiveTaskInfoAsync(function, lowerLimit, upperLimit, integrationMethod, iterations, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> receiveTaskInfoAsync(String function, String lowerLimit, String upperLimit, int integrationMethod, int iterations)
    {
        return _iceI_receiveTaskInfoAsync(function, lowerLimit, upperLimit, integrationMethod, iterations, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> receiveTaskInfoAsync(String function, String lowerLimit, String upperLimit, int integrationMethod, int iterations, java.util.Map<String, String> context)
    {
        return _iceI_receiveTaskInfoAsync(function, lowerLimit, upperLimit, integrationMethod, iterations, context, false);
    }

    /**
     * @hidden
     * @param iceP_function -
     * @param iceP_lowerLimit -
     * @param iceP_upperLimit -
     * @param iceP_integrationMethod -
     * @param iceP_iterations -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_receiveTaskInfoAsync(String iceP_function, String iceP_lowerLimit, String iceP_upperLimit, int iceP_integrationMethod, int iceP_iterations, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "receiveTaskInfo", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_function);
                     ostr.writeString(iceP_lowerLimit);
                     ostr.writeString(iceP_upperLimit);
                     ostr.writeInt(iceP_integrationMethod);
                     ostr.writeInt(iceP_iterations);
                 }, null);
        return f;
    }

    default Task getTask()
    {
        return getTask(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Task getTask(java.util.Map<String, String> context)
    {
        return _iceI_getTaskAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Task> getTaskAsync()
    {
        return _iceI_getTaskAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Task> getTaskAsync(java.util.Map<String, String> context)
    {
        return _iceI_getTaskAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Task> _iceI_getTaskAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Task> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getTask", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     final com.zeroc.IceInternal.Holder<Task> ret = new com.zeroc.IceInternal.Holder<>();
                     istr.readValue(v -> ret.value = v, Task.class);
                     istr.readPendingValues();
                     return ret.value;
                 });
        return f;
    }

    default void addPartialResult(double resultIntegral)
    {
        addPartialResult(resultIntegral, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addPartialResult(double resultIntegral, java.util.Map<String, String> context)
    {
        _iceI_addPartialResultAsync(resultIntegral, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addPartialResultAsync(double resultIntegral)
    {
        return _iceI_addPartialResultAsync(resultIntegral, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addPartialResultAsync(double resultIntegral, java.util.Map<String, String> context)
    {
        return _iceI_addPartialResultAsync(resultIntegral, context, false);
    }

    /**
     * @hidden
     * @param iceP_resultIntegral -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addPartialResultAsync(double iceP_resultIntegral, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addPartialResult", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeDouble(iceP_resultIntegral);
                 }, null);
        return f;
    }

    default void attachWorker(WorkerInterfacePrx subscriber)
    {
        attachWorker(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void attachWorker(WorkerInterfacePrx subscriber, java.util.Map<String, String> context)
    {
        _iceI_attachWorkerAsync(subscriber, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> attachWorkerAsync(WorkerInterfacePrx subscriber)
    {
        return _iceI_attachWorkerAsync(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> attachWorkerAsync(WorkerInterfacePrx subscriber, java.util.Map<String, String> context)
    {
        return _iceI_attachWorkerAsync(subscriber, context, false);
    }

    /**
     * @hidden
     * @param iceP_subscriber -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_attachWorkerAsync(WorkerInterfacePrx iceP_subscriber, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "attachWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_subscriber);
                 }, null);
        return f;
    }

    default void deattachWorker(WorkerInterfacePrx subscriber)
    {
        deattachWorker(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void deattachWorker(WorkerInterfacePrx subscriber, java.util.Map<String, String> context)
    {
        _iceI_deattachWorkerAsync(subscriber, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> deattachWorkerAsync(WorkerInterfacePrx subscriber)
    {
        return _iceI_deattachWorkerAsync(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> deattachWorkerAsync(WorkerInterfacePrx subscriber, java.util.Map<String, String> context)
    {
        return _iceI_deattachWorkerAsync(subscriber, context, false);
    }

    /**
     * @hidden
     * @param iceP_subscriber -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_deattachWorkerAsync(WorkerInterfacePrx iceP_subscriber, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deattachWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_subscriber);
                 }, null);
        return f;
    }

    default void printString(String s)
    {
        printString(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void printString(String s, java.util.Map<String, String> context)
    {
        _iceI_printStringAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> printStringAsync(String s)
    {
        return _iceI_printStringAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> printStringAsync(String s, java.util.Map<String, String> context)
    {
        return _iceI_printStringAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_printStringAsync(String iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "printString", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_s);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MasterInterfacePrx.class, _MasterInterfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MasterInterfacePrx.class, _MasterInterfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MasterInterfacePrx.class, _MasterInterfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MasterInterfacePrx.class, _MasterInterfacePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MasterInterfacePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MasterInterfacePrx.class, _MasterInterfacePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MasterInterfacePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MasterInterfacePrx.class, _MasterInterfacePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MasterInterfacePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MasterInterfacePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MasterInterfacePrx ice_adapterId(String newAdapterId)
    {
        return (MasterInterfacePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MasterInterfacePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MasterInterfacePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MasterInterfacePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MasterInterfacePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MasterInterfacePrx ice_invocationTimeout(int newTimeout)
    {
        return (MasterInterfacePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MasterInterfacePrx ice_connectionCached(boolean newCache)
    {
        return (MasterInterfacePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MasterInterfacePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MasterInterfacePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MasterInterfacePrx ice_secure(boolean b)
    {
        return (MasterInterfacePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MasterInterfacePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MasterInterfacePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MasterInterfacePrx ice_preferSecure(boolean b)
    {
        return (MasterInterfacePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MasterInterfacePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MasterInterfacePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MasterInterfacePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MasterInterfacePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MasterInterfacePrx ice_collocationOptimized(boolean b)
    {
        return (MasterInterfacePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MasterInterfacePrx ice_twoway()
    {
        return (MasterInterfacePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MasterInterfacePrx ice_oneway()
    {
        return (MasterInterfacePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MasterInterfacePrx ice_batchOneway()
    {
        return (MasterInterfacePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MasterInterfacePrx ice_datagram()
    {
        return (MasterInterfacePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MasterInterfacePrx ice_batchDatagram()
    {
        return (MasterInterfacePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MasterInterfacePrx ice_compress(boolean co)
    {
        return (MasterInterfacePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MasterInterfacePrx ice_timeout(int t)
    {
        return (MasterInterfacePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MasterInterfacePrx ice_connectionId(String connectionId)
    {
        return (MasterInterfacePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MasterInterfacePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MasterInterfacePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::MasterInterface";
    }
}
