//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Integral.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class Task extends com.zeroc.Ice.Value
{
    public Task()
    {
        this.function = "";
    }

    public Task(String function, double lowerLimit, double upperLimit, int integrationMethod, int iterations, boolean isInfinite)
    {
        this.function = function;
        this.lowerLimit = lowerLimit;
        this.upperLimit = upperLimit;
        this.integrationMethod = integrationMethod;
        this.iterations = iterations;
        this.isInfinite = isInfinite;
    }

    public String function;

    public double lowerLimit;

    public double upperLimit;

    public int integrationMethod;

    public int iterations;

    public boolean isInfinite;

    public Task clone()
    {
        return (Task)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Demo::Task";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -503164163L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(function);
        ostr_.writeDouble(lowerLimit);
        ostr_.writeDouble(upperLimit);
        ostr_.writeInt(integrationMethod);
        ostr_.writeInt(iterations);
        ostr_.writeBool(isInfinite);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        function = istr_.readString();
        lowerLimit = istr_.readDouble();
        upperLimit = istr_.readDouble();
        integrationMethod = istr_.readInt();
        iterations = istr_.readInt();
        isInfinite = istr_.readBool();
        istr_.endSlice();
    }
}
